const palette = [
    'bg-blue-500/85 border-blue-600',
    'bg-emerald-500/85 border-emerald-600',
    'bg-violet-500/85 border-violet-600',
    'bg-amber-500/85 border-amber-600',
    'bg-rose-500/85 border-rose-600',
    'bg-cyan-500/85 border-cyan-600',
    'bg-orange-500/85 border-orange-600',
    'bg-indigo-500/85 border-indigo-600',
];

const paletteHex = [
    '#3b82f6',
    '#10b981',
    '#8b5cf6',
    '#f59e0b',
    '#f43f5e',
    '#06b6d4',
    '#f97316',
    '#6366f1',
];

const indonesianDays = [
    'Minggu',
    'Senin',
    'Selasa',
    'Rabu',
    'Kamis',
    'Jumat',
    'Sabtu',
];

const indonesianMonths = [
    'Januari',
    'Februari',
    'Maret',
    'April',
    'Mei',
    'Juni',
    'Juli',
    'Agustus',
    'September',
    'Oktober',
    'November',
    'Desember',
];

export function courseColorClass(courseId: number): string {
    return palette[courseId % palette.length];
}

export function courseColorHex(courseId: number): string {
    return paletteHex[courseId % paletteHex.length];
}

export function formatGeneratedStamp(
    date: Date = new Date(),
    appName: string = 'KRS Planner',
): string {
    const dayName = indonesianDays[date.getDay()];
    const monthName = indonesianMonths[date.getMonth()];
    const hours = String(date.getHours()).padStart(2, '0');
    const minutes = String(date.getMinutes()).padStart(2, '0');

    return `Generated by ${appName} • ${dayName}, ${date.getDate()} ${monthName} ${date.getFullYear()} ${hours}:${minutes}`;
}

export function timeToMinutes(time: string): number {
    const [hours, minutes] = time.split(':').map(Number);

    return hours * 60 + minutes;
}

export function gridPosition(
    startsAt: string,
    endsAt: string,
    gridStart: string,
    slotMinutes: number,
): { top: number; height: number } {
    const start = timeToMinutes(startsAt);
    const end = timeToMinutes(endsAt);
    const gridStartMinutes = timeToMinutes(gridStart);

    const top = ((start - gridStartMinutes) / slotMinutes) * 100 / 22;
    const height = ((end - start) / slotMinutes) * 100 / 22;

    return {
        top: Math.max(0, top * 22),
        height: Math.max(2, height * 22),
    };
}
