<?php

namespace App\Support;

use Carbon\CarbonInterface;
use Illuminate\Support\Facades\Date;

class GeneratedStamp
{
    public static function label(?CarbonInterface $at = null, ?string $appName = null): string
    {
        $at = ($at ?? Date::now())->timezone(config('app.timezone'))->locale('id');
        $appName ??= (string) config('app.name');

        return sprintf(
            'Generated by %s • %s',
            $appName,
            $at->translatedFormat('l, j F Y H:i'),
        );
    }
}
