<?php

use App\Support\GeneratedStamp;
use Illuminate\Support\Facades\Date;

test('generated stamp includes the app name with indonesian day and date', function () {
    Date::setTestNow(Date::parse('2026-08-18 17:43:00', 'UTC'));

    $stamp = GeneratedStamp::label(null, 'KRS Planner');

    expect($stamp)->toContain('Generated by')
        ->and($stamp)->toContain('KRS Planner')
        ->and($stamp)->toContain('Selasa')
        ->and($stamp)->toContain('18')
        ->and($stamp)->toContain('Agustus')
        ->and($stamp)->toContain('2026')
        ->and($stamp)->toContain('17:43');
});
